name: ONT_SAMPLER Singularity Image CI

on:
  push:
    paths:
      - modules/local/ont_sampler/**
  workflow_dispatch:

env:
  img_name: jimmyliu1326/ont_sampler
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Build Container
        working-directory: ./modules/local/ont_sampler/
        env:
          recipe: singularity.def
        run: |
            sudo env \
              HOME=/root \
              APPTAINER_CACHEDIR=/tmp/apptainer-cache \
              sudo -E apptainer build container.sif ${{ env.recipe }}

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.MY_PAT }}" |
            apptainer registry login \
              --username "${{ secrets.GHCR_USERNAME }}" \
              --password-stdin \
              oras://ghcr.io

      - name: Push container
        working-directory: ./modules/local/ont_sampler/
        run: |
          apptainer push \
            container.sif \
            "oras://ghcr.io/${{ env.img_name }}:latest"