name: ONT_SAMPLER Singularity Image CI

on:
  push:
    paths:
      - modules/local/ont_sampler/**
  workflow_dispatch:

env:
  img_name: jimmyliu1326/ont_sampler
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-containers:
    runs-on: ubuntu-latest

    container:
      image: quay.io/singularity/singularity:v3.8.1
      options: --privileged

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          wget -q \
            "https://github.com/apptainer/apptainer/releases/download/v${APPTAINER_VERSION}/apptainer_${APPTAINER_VERSION}_amd64.deb"

          sudo apt-get update
          sudo apt-get install -y \
            "./apptainer_${APPTAINER_VERSION}_amd64.deb"

          apptainer --version

      - name: Build Container
        working-directory: ./modules/local/ont_sampler/
        env:
          recipe: singularity.def
        run: |
            sudo -E apptainer build container.sif ${{ env.recipe }}

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.MY_PAT }}" |
            apptainer registry login \
              --username "${{ secrets.GHCR_USERNAME }}" \
              --password-stdin \
              oras://ghcr.io

      - name: Push container
        working-directory: ./modules/local/ont_sampler/
        run: |
          apptainer push \
            container.sif \
            "oras://ghcr.io/${{ env.img_name }}:latest"